.PHONY: clean All

All:
	@echo "----------Building project:[ dynamicclient - Debug ]----------"
	@cd "dynamicclient" && "$(MAKE)" -f  "dynamicclient.mk"
clean:
	@echo "----------Cleaning project:[ dynamicclient - Debug ]----------"
	@cd "dynamicclient" && "$(MAKE)" -f  "dynamicclient.mk" clean
