.PHONY: clean All

All:
	@echo "----------Building project:[ structsize - Debug ]----------"
	@cd "structsize" && "$(MAKE)" -f  "structsize.mk"
clean:
	@echo "----------Cleaning project:[ structsize - Debug ]----------"
	@cd "structsize" && "$(MAKE)" -f  "structsize.mk" clean
