.PHONY: clean All

All:
	@echo "----------Building project:[ receiver - Debug ]----------"
	@cd "writer" && "$(MAKE)" -f  "receiver.mk"
clean:
	@echo "----------Cleaning project:[ receiver - Debug ]----------"
	@cd "writer" && "$(MAKE)" -f  "receiver.mk" clean
