.PHONY: clean All

All:
	@echo "----------Building project:[ twowaycommunication - Debug ]----------"
	@cd "twowaycommunication" && "$(MAKE)" -f  "twowaycommunication.mk"
clean:
	@echo "----------Cleaning project:[ twowaycommunication - Debug ]----------"
	@cd "twowaycommunication" && "$(MAKE)" -f  "twowaycommunication.mk" clean
