.PHONY: clean All

All:
	@echo "----------Building project:[ client1 - Debug ]----------"
	@cd "client1" && "$(MAKE)" -f  "client1.mk"
clean:
	@echo "----------Cleaning project:[ client1 - Debug ]----------"
	@cd "client1" && "$(MAKE)" -f  "client1.mk" clean
