.PHONY: clean All

All:
	@echo "----------Building project:[ Asharedmemory_semaphore - Debug ]----------"
	@cd "Asharedmemory_semaphore" && "$(MAKE)" -f  "Asharedmemory_semaphore.mk"
clean:
	@echo "----------Cleaning project:[ Asharedmemory_semaphore - Debug ]----------"
	@cd "Asharedmemory_semaphore" && "$(MAKE)" -f  "Asharedmemory_semaphore.mk" clean
