.PHONY: clean All

All:
	@echo "----------Building project:[ forkmemorymap - Debug ]----------"
	@cd "forkmemorymap" && "$(MAKE)" -f  "forkmemorymap.mk"
clean:
	@echo "----------Cleaning project:[ forkmemorymap - Debug ]----------"
	@cd "forkmemorymap" && "$(MAKE)" -f  "forkmemorymap.mk" clean
