.PHONY: clean All

All:
	@echo "----------Building project:[ tcpcharclient - Debug ]----------"
	@cd "tcpcharclient" && "$(MAKE)" -f  "tcpcharclient.mk"
clean:
	@echo "----------Cleaning project:[ tcpcharclient - Debug ]----------"
	@cd "tcpcharclient" && "$(MAKE)" -f  "tcpcharclient.mk" clean
