.PHONY: clean All

All:
	@echo "----------Building project:[ nothreadnoselectclient - Debug ]----------"
	@cd "nothreadnoselectclient" && "$(MAKE)" -f  "nothreadnoselectclient.mk"
clean:
	@echo "----------Cleaning project:[ nothreadnoselectclient - Debug ]----------"
	@cd "nothreadnoselectclient" && "$(MAKE)" -f  "nothreadnoselectclient.mk" clean
