.PHONY: clean All

All:
	@echo "----------Building project:[ version4 - Debug ]----------"
	@cd "version4" && "$(MAKE)" -f  "version4.mk"
clean:
	@echo "----------Cleaning project:[ version4 - Debug ]----------"
	@cd "version4" && "$(MAKE)" -f  "version4.mk" clean
