.PHONY: clean All

All:
	@echo "----------Building project:[ version1 - Debug ]----------"
	@cd "version1" && "$(MAKE)" -f  "version1.mk"
clean:
	@echo "----------Cleaning project:[ version1 - Debug ]----------"
	@cd "version1" && "$(MAKE)" -f  "version1.mk" clean
