.PHONY: clean All

All:
	@echo "----------Building project:[ conditinal - Debug ]----------"
	@cd "conditinal" && "$(MAKE)" -f  "conditinal.mk"
clean:
	@echo "----------Cleaning project:[ conditinal - Debug ]----------"
	@cd "conditinal" && "$(MAKE)" -f  "conditinal.mk" clean
