.PHONY: clean All

All:
	@echo "----------Building project:[ BST - Debug ]----------"
	@cd "BST" && "$(MAKE)" -f  "BST.mk"
clean:
	@echo "----------Cleaning project:[ BST - Debug ]----------"
	@cd "BST" && "$(MAKE)" -f  "BST.mk" clean
