.PHONY: clean All

All:
	@echo "----------Building project:[ conditionalmutex - Debug ]----------"
	@cd "conditionalmutex" && "$(MAKE)" -f  "conditionalmutex.mk"
clean:
	@echo "----------Cleaning project:[ conditionalmutex - Debug ]----------"
	@cd "conditionalmutex" && "$(MAKE)" -f  "conditionalmutex.mk" clean
