.PHONY: clean All

All:
	@echo "----------Building project:[ projectextern - Debug ]----------"
	@cd "projectextern" && "$(MAKE)" -f  "projectextern.mk"
clean:
	@echo "----------Cleaning project:[ projectextern - Debug ]----------"
	@cd "projectextern" && "$(MAKE)" -f  "projectextern.mk" clean
