.PHONY: clean All

All:
	@echo "----------Building project:[ sender1 - Debug ]----------"
	@cd "sender1" && "$(MAKE)" -f  "sender1.mk"
clean:
	@echo "----------Cleaning project:[ sender1 - Debug ]----------"
	@cd "sender1" && "$(MAKE)" -f  "sender1.mk" clean
