.PHONY: clean All

All:
	@echo "----------Building project:[ producer_consumer - Debug ]----------"
	@cd "producer_consumer" && "$(MAKE)" -f  "producer_consumer.mk"
clean:
	@echo "----------Cleaning project:[ producer_consumer - Debug ]----------"
	@cd "producer_consumer" && "$(MAKE)" -f  "producer_consumer.mk" clean
