.PHONY: clean All

All:
	@echo "----------Building project:[ dining_cnsumer - Debug ]----------"
	@cd "dining_cnsumer" && "$(MAKE)" -f  "dining_cnsumer.mk"
clean:
	@echo "----------Cleaning project:[ dining_cnsumer - Debug ]----------"
	@cd "dining_cnsumer" && "$(MAKE)" -f  "dining_cnsumer.mk" clean
