.PHONY: clean All

All:
	@echo "----------Building project:[ bankbalancemutexx - Debug ]----------"
	@cd "bankbalancemutexx" && "$(MAKE)" -f  "bankbalancemutexx.mk"
clean:
	@echo "----------Cleaning project:[ bankbalancemutexx - Debug ]----------"
	@cd "bankbalancemutexx" && "$(MAKE)" -f  "bankbalancemutexx.mk" clean
