.PHONY: clean All

All:
	@echo "----------Building project:[ dup2 - Debug ]----------"
	@cd "dup2" && "$(MAKE)" -f  "dup2.mk"
clean:
	@echo "----------Cleaning project:[ dup2 - Debug ]----------"
	@cd "dup2" && "$(MAKE)" -f  "dup2.mk" clean
