.PHONY: clean All

All:
	@echo "----------Building project:[ namedsemaphore - Debug ]----------"
	@cd "namedsemaphore" && "$(MAKE)" -f  "namedsemaphore.mk"
clean:
	@echo "----------Cleaning project:[ namedsemaphore - Debug ]----------"
	@cd "namedsemaphore" && "$(MAKE)" -f  "namedsemaphore.mk" clean
